import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import BottomBar from "@/components/ui/general/BottomBar";
import "./globals.css";
import { Providers } from "@/components/ui/general/Providers";
import NavbarServer from "@/components/ui/general/NabvarServer";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MOCK_NAV_PROPS = {
  users: 124,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} min-h-screen bg-gradient-one font-sans antialiased`}
      >
        <Providers>
          <NavbarServer />
          {children}
          <BottomBar />
        </Providers>
      </body>
    </html>
  );
}
